//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace work_01_Authentication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stuff
    {
        public int id { get; set; }
        public string StufName { get; set; }
        public System.DateTime JoinDate { get; set; }
        public string ContactNo { get; set; }
        public decimal Salary { get; set; }
        public string Address { get; set; }
        public string Picture { get; set; }
    }
}
